- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
      - name: create security group
        ec2_group:
          name: dmz
          vpc_id: vpc-06202e3efee5b0b86
          description: an example ec2 group
          region: ap-northeast-1
          rules:
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
        register: group


      - name: create RDS subnet group
        rds_subnet_group:
          state: present
          name: my_rds_subnets
          description: my_description
          region: ap-northeast-1
          subnets: 
            - subnet-0877ca1231546484b
            - subnet-0b639e9b3ae135332



      - name: create RDS instance
        rds:
         command: modify
#Parameter subnet should be present for command: create only, not for modify
#         subnet: my_rds_subnets 
         instance_name: dbserver-1
         db_engine: MySQL
         size: 20
         instance_type: db.t2.micro
         username: mysql_admin
         password: 1nsecure
         region: ap-northeast-1
         backup_retention: 0
         multi_zone: no
#Parameter tags should be present for command: create only, not for modify
#         tags:
#           Environment: testing
#           Application: cms
        register: group

      - name: create ec2 instance
        ec2:
          image: ami-079e6fb1e856e80c1
          vpc_subnet_id: subnet-067f61b01c7d123f3
          wait: yes
          instance_type: t2.micro
          region: ap-northeast-1
          count_tag:
            Name: appserver
          exact_count: 1
        register: ec2


